system:	libopus.a libwav.a libpng16.a libbpg.a
	@echo done	


libopus.a: opus-1.1.tar.gz
#		bash build_opus.sh

libwav.a: wavtools-0.2.1.tar.gz
#		bash build_wav.sh

libpng16.a: 

libbpg.a: libbpg-0.9.8.tar.gz
	bash build_libbpg_server.sh

