

#define WORLD__oparen_Ljava_slash_lang_slash_String_semicolon__cparen_I "(Ljava/lang/String;)I"
#define WORLD_255_dot_255_dot_255_dot_255 "255.255.255.255"
#define WORLD_a0_dot_rawrgb "a0.rawrgb"
#define WORLD_application_slash_silentradiance "application/silentradiance"
#define WORLD_application_slash_silentradiancesneakysevensnake "application/silentradiancesneakysevensnake"
#define WORLD_AUDIO_INPUT_FLAG_FAST_denied_by_client_semicolon__transfer__pct_d_comma__track__pct_u_Hz_comma__primary__pct_u_Hz "AUDIO_INPUT_FLAG_FAST denied by client; transfer %d, track %u Hz, primary %u Hz"
#define WORLD_AUDIO_INPUT_FLAG_FAST_successful_semicolon__frameCount__pct_zu "AUDIO_INPUT_FLAG_FAST successful; frameCount %zu"
#define WORLD_AUDIO_INPUT_FLAG_FAST_denied_by_server_semicolon__frameCount__pct_zu "AUDIO_INPUT_FLAG_FAST denied by server; frameCount %zu"
#define WORLD_bind_oparen__cparen__failed "bind() failed"
#define WORLD_Buffer_Size_and_sample_rate "Buffer Size and sample rate"
#define WORLD_ButtonFlags "ButtonFlags"
#define WORLD_Can_qt_t_recovery_from_suspend_comma__prepare_failed_colon___pct_s_lf_ "Can't recovery from suspend, prepare failed: %s\n"
#define WORLD_Can_qt_t_recovery_from_underrun_comma__prepare_failed_colon___pct_s_lf_ "Can't recovery from underrun, prepare failed: %s\n"
#define WORLD__checksum_ " checksum "
#define WORLD_combine_raw_vids_a_dot_rawrgb "a.rawrgb"
#define WORLD_combine_raw_vids_a_dot_rgb "a.rgb"
#define WORLD_combine_raw_vids_rb "rb"
#define WORLD_combine_raw_vids_r "r"
#define WORLD_combine_raw_vids_w "w"
#define WORLD_Could_not_get_audioflinger "Could not get audioflinger"
#define WORLD_Could_not_load_GLES2_functions_lf_ "Could not load GLES2 functions\n"
#define WORLD_Couldn_qt_t_load_GLES2_function__pct_s_colon___pct_s "Couldn't load GLES2 function %s: %s"
#define WORLD_curl_web_stream_fread7 "fread7"
#define WORLD_curl_web_stream_read7 "read7"
#define WORLD_curl_web_stream_read_ "read "
#define WORLD_curl_web_stream_r "r"
#define WORLD_decoded_frame "decoded frame"
#define WORLD_decode_srd_r "r"
#define WORLD_display_default_default "default"
#define WORLD_display_default_rb "rb"
#define WORLD_display_dennis1_Dennis1 "Dennis1"
#define WORLD_display_display_main_linux_a "a"
#define WORLD_display_display_main_linux_a_dot_rawrgb "a.rawrgb"
#define WORLD_display_display_set_ ""
#define WORLD_display_display_set__ " "
#define WORLD_display_display_set__pct_s_pct_d "%s%d"
#define WORLD_display_helper_ ""
#define WORLD_display_luis1_luis1 "luis1"
#define WORLD_DisplaySetOrder "DisplaySetOrder"
#define WORLD_display_staff__pct_s_pct_s_pct_s "%s%s%s"
#define WORLD_display_top_menu_top_menu "top_menu"
#define WORLD_display_triangle_1 "1"
#define WORLD_emscripten_web_stream__pct_16ld "%16ld"
#define WORLD_encoded_frame "encoded frame"
#define WORLD_Fatal__oparen_internal_cparen__error_in__pct_s_comma__line__pct_d_colon___pct_s_lf_ "Fatal (internal) error in %s, line %d: %s\n"
#define WORLD_file_receiver__minus_ "-"
#define WORLD_file_receiver_r "r"
#define WORLD_firstconv7 "firstconv7"
#define WORLD_firstconv "firstconv"
#define WORLD_First_test_read_ "First test read "
#define WORLD__frame__pct_d_checksum_ " frame %d checksum "
#define WORLD_FunctionFlags "FunctionFlags"
#define WORLD_FunctionUChoose "FunctionUChoose"
#define WORLD_getPrimaryOutputSamplingRate_failed "getPrimaryOutputSamplingRate failed"
#define WORLD_GL_INAVLID_ENUM "GL_INAVLID_ENUM"
#define WORLD_GL_INVALID_FRAMEBUFFER_OPERATION "GL_INVALID_FRAMEBUFFER_OPERATION"
#define WORLD_GL_INVALID_OPERATION "GL_INVALID_OPERATION"
#define WORLD_GL_INVALID_VALUE "GL_INVALID_VALUE"
#define WORLD_GL_OUT_OF_MEMORY "GL_OUT_OF_MEMORY"
#define WORLD_glue_android_execsql "execsql"
#define WORLD_glue_alsa_ ""
#define WORLD_glue_js_ ""
#define WORLD_glue_win64_ ""
#define WORLD_larry_harvey "larry_harvey"
#define WORLD_main_menu "main_menu"
#define WORLD_network_cube "network_cube"
#define WORLD__oparen_Ljava_slash_lang_slash_String_semicolon__cparen_I "(Ljava/lang/String;)I"
#define WORLD_packet_summary_SR01 "SR01"
#define WORLD__pct_c__pct_s__pct_f__pct_f__pct_f "%c %s %f %f %f"
#define WORLD__pct_s_slash__qm_t_equals__pct_s_amp_p_equals__pct_s_amp_l_equals__pct_s "%s/?t=%s&p=%s&l=%s"
#define WORLD_SR_PROTOCOL_SR00 "sr00"
#define WORLD_SR_PROTOCOL_SR01 "sr01"
#define WORLD_OpenSLWrap_Size__colon_ "Size :"
#define WORLD___amp__Rate_colon__ " & Rate: "
#define WORLD__pct_d_dot__pct_d_dot__pct_d_dot__pct_d "%d.%d.%d.%d"
#define WORLD_purple_string "purple_string"
#define WORLD__qm_t_equals__pct_s_amp_p_equals__pct_s_amp_l_equals__pct_s "?t=%s&p=%s&l=%s"
#define WORLD__queue__pct_d_range__pct_d_to__pct_d_lf_ "	queue %d	range	%d to %d\n"
#define WORLD_receiver_alsa6_default "default"
#define WORLD_receiver_alsa6_r "r"
#define WORLD_receiver_alsa6_w "w"
#define WORLD_receiver_alsa_default "default"
#define WORLD_receiver_alsa_r "r"
#define WORLD_receiver_alsa_w "w"
#define WORLD_receiver_no_sound__crud_ " crud "
#define WORLD_receiver_no_sound__minus_b "-b"
#define WORLD_receiver_no_sound__minus_t "-t"
#define WORLD_record_dot_srd "record.srd"
#define WORLD_recvfrom_oparen__cparen__failed "recvfrom() failed"
#define WORLD_Renderer____colon___pct_s_lf_ "Renderer   : %s\n"
#define WORLD_SDL_GetDisplayBounds_failed_colon___pct_s "SDL_GetDisplayBounds failed: %s"
#define WORLD_SDL_GetDisplayDPI_failed_colon___pct_s "SDL_GetDisplayDPI failed: %s"
#define WORLD_SDL_GL_CreateContext_oparen__cparen__colon___pct_s_lf_ "SDL_GL_CreateContext(): %s\n"
#define WORLD_SDL_GL_MakeCurrent_oparen__cparen__colon___pct_s_lf_ "SDL_GL_MakeCurrent(): %s\n"
#define WORLD_select_one_int "select_one_int"
#define WORLD_sendto_failed_with_error_colon___pct_d_lf_ "sendto failed with error: %d\n"
#define WORLD_simple_curl_web_stream_fread7 "fread7"
#define WORLD_simple_curl_web_stream_read7 "read7"
#define WORLD_simple_curl_web_stream_read_ "read "
#define WORLD_simple_curl_web_stream_r "r"
#define WORLD_simple_sound_alsa_default "default"
#define WORLD_socket_oparen__cparen__failed "socket() failed"
#define WORLD_sound_alsa_default "default"
#define WORLD_soundin_portaudio_default "default"
#define WORLD_unable_to_open_pcm_device_colon___pct_s_lf_ "unable to open pcm device: %s\n"
#define WORLD_unable_to_set_hw_parameters_colon___pct_s_lf_ "unable to set hw parameters: %s\n"
#define WORLD_use_raw_vid_for_layer_background_rb "rb"
#define WORLD_usual_read "usual_read"
#define WORLD_Vendor______colon___pct_s_lf_ "Vendor     : %s\n"
#define WORLD_Version_____colon___pct_s_lf_ "Version    : %s\n"
#define WORLD_win64_network_receiver_42 "42"
#define WORLD_windowshop "windowshop"
#define WORLD_Write_error_colon___pct_d__pct_s_lf_ "Write error: %d %s\n"
#define WORLD_Write_error_colon___pct_s_lf_ "Write error: %s\n"
