/* Autogenerated by hxtools bin2c */
#ifndef IMPACT_H
#define IMPACT_H 1

#ifdef __cplusplus
extern "C" {
#endif


#define IMPACT_TTF_SIZE 136076
extern const unsigned char bin2c_impact_ttf[136076];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* IMPACT_H */
