/* generated with convert_gles2funcs_into_gles_define_overs.sno 
  Generator by Hibbard M. Engler
  */
#ifndef _H_GLES_DEFINE_OVERS
#define _H_GLES_DEFINE_OVERS 1

#ifndef GLES2_DEFINE_OVERS_CONTEXT
#define GLES2_DEFINE_OVERS_CONTEXT ctx
#endif

/* generated with convert_gl2_h_into_gles2funcs_h.sno 
  Generator by Hibbard M. Engler

  */

#define glActiveTexture(...) GLES2_DEFINE_OVERS_CONTEXT.glActiveTexture(__VA_ARGS__)
#define glAttachShader(...) GLES2_DEFINE_OVERS_CONTEXT.glAttachShader(__VA_ARGS__)
#define glBindAttribLocation(...) GLES2_DEFINE_OVERS_CONTEXT.glBindAttribLocation(__VA_ARGS__)
#define glBindBuffer(...) GLES2_DEFINE_OVERS_CONTEXT.glBindBuffer(__VA_ARGS__)
#define glBindFramebuffer(...) GLES2_DEFINE_OVERS_CONTEXT.glBindFramebuffer(__VA_ARGS__)
#define glBindRenderbuffer(...) GLES2_DEFINE_OVERS_CONTEXT.glBindRenderbuffer(__VA_ARGS__)
#define glBindTexture(...) GLES2_DEFINE_OVERS_CONTEXT.glBindTexture(__VA_ARGS__)
#define glBlendColor(...) GLES2_DEFINE_OVERS_CONTEXT.glBlendColor(__VA_ARGS__)
#define glBlendEquation(...) GLES2_DEFINE_OVERS_CONTEXT.glBlendEquation(__VA_ARGS__)
#define glBlendEquationSeparate(...) GLES2_DEFINE_OVERS_CONTEXT.glBlendEquationSeparate(__VA_ARGS__)
#define glBlendFunc(...) GLES2_DEFINE_OVERS_CONTEXT.glBlendFunc(__VA_ARGS__)
#define glBlendFuncSeparate(...) GLES2_DEFINE_OVERS_CONTEXT.glBlendFuncSeparate(__VA_ARGS__)
#define glBufferData(...) GLES2_DEFINE_OVERS_CONTEXT.glBufferData(__VA_ARGS__)
#define glBufferSubData(...) GLES2_DEFINE_OVERS_CONTEXT.glBufferSubData(__VA_ARGS__)
#define glCheckFramebufferStatus(...) GLES2_DEFINE_OVERS_CONTEXT.glCheckFramebufferStatus(__VA_ARGS__)
#define glClear(...) GLES2_DEFINE_OVERS_CONTEXT.glClear(__VA_ARGS__)
#define glClearColor(...) GLES2_DEFINE_OVERS_CONTEXT.glClearColor(__VA_ARGS__)
#define glClearDepthf(...) GLES2_DEFINE_OVERS_CONTEXT.glClearDepthf(__VA_ARGS__)
#define glClearStencil(...) GLES2_DEFINE_OVERS_CONTEXT.glClearStencil(__VA_ARGS__)
#define glColorMask(...) GLES2_DEFINE_OVERS_CONTEXT.glColorMask(__VA_ARGS__)
#define glCompileShader(...) GLES2_DEFINE_OVERS_CONTEXT.glCompileShader(__VA_ARGS__)
#define glCompressedTexImage2D(...) GLES2_DEFINE_OVERS_CONTEXT.glCompressedTexImage2D(__VA_ARGS__)
#define glCompressedTexSubImage2D(...) GLES2_DEFINE_OVERS_CONTEXT.glCompressedTexSubImage2D(__VA_ARGS__)
#define glCopyTexImage2D(...) GLES2_DEFINE_OVERS_CONTEXT.glCopyTexImage2D(__VA_ARGS__)
#define glCopyTexSubImage2D(...) GLES2_DEFINE_OVERS_CONTEXT.glCopyTexSubImage2D(__VA_ARGS__)
#define glCreateProgram(...) GLES2_DEFINE_OVERS_CONTEXT.glCreateProgram(__VA_ARGS__)
#define glCreateShader(...) GLES2_DEFINE_OVERS_CONTEXT.glCreateShader(__VA_ARGS__)
#define glCullFace(...) GLES2_DEFINE_OVERS_CONTEXT.glCullFace(__VA_ARGS__)
#define glDeleteBuffers(...) GLES2_DEFINE_OVERS_CONTEXT.glDeleteBuffers(__VA_ARGS__)
#define glDeleteFramebuffers(...) GLES2_DEFINE_OVERS_CONTEXT.glDeleteFramebuffers(__VA_ARGS__)
#define glDeleteProgram(...) GLES2_DEFINE_OVERS_CONTEXT.glDeleteProgram(__VA_ARGS__)
#define glDeleteRenderbuffers(...) GLES2_DEFINE_OVERS_CONTEXT.glDeleteRenderbuffers(__VA_ARGS__)
#define glDeleteShader(...) GLES2_DEFINE_OVERS_CONTEXT.glDeleteShader(__VA_ARGS__)
#define glDeleteTextures(...) GLES2_DEFINE_OVERS_CONTEXT.glDeleteTextures(__VA_ARGS__)
#define glDepthFunc(...) GLES2_DEFINE_OVERS_CONTEXT.glDepthFunc(__VA_ARGS__)
#define glDepthMask(...) GLES2_DEFINE_OVERS_CONTEXT.glDepthMask(__VA_ARGS__)
#define glDepthRangef(...) GLES2_DEFINE_OVERS_CONTEXT.glDepthRangef(__VA_ARGS__)
#define glDetachShader(...) GLES2_DEFINE_OVERS_CONTEXT.glDetachShader(__VA_ARGS__)
#define glDisable(...) GLES2_DEFINE_OVERS_CONTEXT.glDisable(__VA_ARGS__)
#define glDisableVertexAttribArray(...) GLES2_DEFINE_OVERS_CONTEXT.glDisableVertexAttribArray(__VA_ARGS__)
#define glDrawArrays(...) GLES2_DEFINE_OVERS_CONTEXT.glDrawArrays(__VA_ARGS__)
#define glDrawElements(...) GLES2_DEFINE_OVERS_CONTEXT.glDrawElements(__VA_ARGS__)
#define glEnable(...) GLES2_DEFINE_OVERS_CONTEXT.glEnable(__VA_ARGS__)
#define glEnableVertexAttribArray(...) GLES2_DEFINE_OVERS_CONTEXT.glEnableVertexAttribArray(__VA_ARGS__)
#define glFinish(...) GLES2_DEFINE_OVERS_CONTEXT.glFinish(__VA_ARGS__)
#define glFlush(...) GLES2_DEFINE_OVERS_CONTEXT.glFlush(__VA_ARGS__)
#define glFramebufferRenderbuffer(...) GLES2_DEFINE_OVERS_CONTEXT.glFramebufferRenderbuffer(__VA_ARGS__)
#define glFramebufferTexture2D(...) GLES2_DEFINE_OVERS_CONTEXT.glFramebufferTexture2D(__VA_ARGS__)
#define glFrontFace(...) GLES2_DEFINE_OVERS_CONTEXT.glFrontFace(__VA_ARGS__)
#define glGenBuffers(...) GLES2_DEFINE_OVERS_CONTEXT.glGenBuffers(__VA_ARGS__)
#define glGenerateMipmap(...) GLES2_DEFINE_OVERS_CONTEXT.glGenerateMipmap(__VA_ARGS__)
#define glGenFramebuffers(...) GLES2_DEFINE_OVERS_CONTEXT.glGenFramebuffers(__VA_ARGS__)
#define glGenRenderbuffers(...) GLES2_DEFINE_OVERS_CONTEXT.glGenRenderbuffers(__VA_ARGS__)
#define glGenTextures(...) GLES2_DEFINE_OVERS_CONTEXT.glGenTextures(__VA_ARGS__)
#define glGetActiveAttrib(...) GLES2_DEFINE_OVERS_CONTEXT.glGetActiveAttrib(__VA_ARGS__)
#define glGetActiveUniform(...) GLES2_DEFINE_OVERS_CONTEXT.glGetActiveUniform(__VA_ARGS__)
#define glGetAttachedShaders(...) GLES2_DEFINE_OVERS_CONTEXT.glGetAttachedShaders(__VA_ARGS__)
#define glGetAttribLocation(...) GLES2_DEFINE_OVERS_CONTEXT.glGetAttribLocation(__VA_ARGS__)
#define glGetBooleanv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetBooleanv(__VA_ARGS__)
#define glGetBufferParameteriv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetBufferParameteriv(__VA_ARGS__)
#define glGetError(...) GLES2_DEFINE_OVERS_CONTEXT.glGetError(__VA_ARGS__)
#define glGetFloatv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetFloatv(__VA_ARGS__)
#define glGetFramebufferAttachmentParameteriv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetFramebufferAttachmentParameteriv(__VA_ARGS__)
#define glGetIntegerv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetIntegerv(__VA_ARGS__)
#define glGetProgramiv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetProgramiv(__VA_ARGS__)
#define glGetProgramInfoLog(...) GLES2_DEFINE_OVERS_CONTEXT.glGetProgramInfoLog(__VA_ARGS__)
#define glGetRenderbufferParameteriv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetRenderbufferParameteriv(__VA_ARGS__)
#define glGetShaderiv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetShaderiv(__VA_ARGS__)
#define glGetShaderInfoLog(...) GLES2_DEFINE_OVERS_CONTEXT.glGetShaderInfoLog(__VA_ARGS__)
#define glGetShaderPrecisionFormat(...) GLES2_DEFINE_OVERS_CONTEXT.glGetShaderPrecisionFormat(__VA_ARGS__)
#define glGetShaderSource(...) GLES2_DEFINE_OVERS_CONTEXT.glGetShaderSource(__VA_ARGS__)
#define glGetString(...) GLES2_DEFINE_OVERS_CONTEXT.glGetString(__VA_ARGS__)
#define glGetTexParameterfv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetTexParameterfv(__VA_ARGS__)
#define glGetTexParameteriv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetTexParameteriv(__VA_ARGS__)
#define glGetUniformfv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetUniformfv(__VA_ARGS__)
#define glGetUniformiv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetUniformiv(__VA_ARGS__)
#define glGetUniformLocation(...) GLES2_DEFINE_OVERS_CONTEXT.glGetUniformLocation(__VA_ARGS__)
#define glGetVertexAttribfv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetVertexAttribfv(__VA_ARGS__)
#define glGetVertexAttribiv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetVertexAttribiv(__VA_ARGS__)
#define glGetVertexAttribPointerv(...) GLES2_DEFINE_OVERS_CONTEXT.glGetVertexAttribPointerv(__VA_ARGS__)
#define glHint(...) GLES2_DEFINE_OVERS_CONTEXT.glHint(__VA_ARGS__)
#define glIsBuffer(...) GLES2_DEFINE_OVERS_CONTEXT.glIsBuffer(__VA_ARGS__)
#define glIsEnabled(...) GLES2_DEFINE_OVERS_CONTEXT.glIsEnabled(__VA_ARGS__)
#define glIsFramebuffer(...) GLES2_DEFINE_OVERS_CONTEXT.glIsFramebuffer(__VA_ARGS__)
#define glIsProgram(...) GLES2_DEFINE_OVERS_CONTEXT.glIsProgram(__VA_ARGS__)
#define glIsRenderbuffer(...) GLES2_DEFINE_OVERS_CONTEXT.glIsRenderbuffer(__VA_ARGS__)
#define glIsShader(...) GLES2_DEFINE_OVERS_CONTEXT.glIsShader(__VA_ARGS__)
#define glIsTexture(...) GLES2_DEFINE_OVERS_CONTEXT.glIsTexture(__VA_ARGS__)
#define glLineWidth(...) GLES2_DEFINE_OVERS_CONTEXT.glLineWidth(__VA_ARGS__)
#define glLinkProgram(...) GLES2_DEFINE_OVERS_CONTEXT.glLinkProgram(__VA_ARGS__)
#define glPixelStorei(...) GLES2_DEFINE_OVERS_CONTEXT.glPixelStorei(__VA_ARGS__)
#define glPolygonOffset(...) GLES2_DEFINE_OVERS_CONTEXT.glPolygonOffset(__VA_ARGS__)
#define glReadPixels(...) GLES2_DEFINE_OVERS_CONTEXT.glReadPixels(__VA_ARGS__)
#define glReleaseShaderCompiler(...) GLES2_DEFINE_OVERS_CONTEXT.glReleaseShaderCompiler(__VA_ARGS__)
#define glRenderbufferStorage(...) GLES2_DEFINE_OVERS_CONTEXT.glRenderbufferStorage(__VA_ARGS__)
#define glSampleCoverage(...) GLES2_DEFINE_OVERS_CONTEXT.glSampleCoverage(__VA_ARGS__)
#define glScissor(...) GLES2_DEFINE_OVERS_CONTEXT.glScissor(__VA_ARGS__)
#define glShaderBinary(...) GLES2_DEFINE_OVERS_CONTEXT.glShaderBinary(__VA_ARGS__)
#define glShaderSource(...) GLES2_DEFINE_OVERS_CONTEXT.glShaderSource(__VA_ARGS__)
#define glStencilFunc(...) GLES2_DEFINE_OVERS_CONTEXT.glStencilFunc(__VA_ARGS__)
#define glStencilFuncSeparate(...) GLES2_DEFINE_OVERS_CONTEXT.glStencilFuncSeparate(__VA_ARGS__)
#define glStencilMask(...) GLES2_DEFINE_OVERS_CONTEXT.glStencilMask(__VA_ARGS__)
#define glStencilMaskSeparate(...) GLES2_DEFINE_OVERS_CONTEXT.glStencilMaskSeparate(__VA_ARGS__)
#define glStencilOp(...) GLES2_DEFINE_OVERS_CONTEXT.glStencilOp(__VA_ARGS__)
#define glStencilOpSeparate(...) GLES2_DEFINE_OVERS_CONTEXT.glStencilOpSeparate(__VA_ARGS__)
#define glTexImage2D(...) GLES2_DEFINE_OVERS_CONTEXT.glTexImage2D(__VA_ARGS__)
#define glTexParameterf(...) GLES2_DEFINE_OVERS_CONTEXT.glTexParameterf(__VA_ARGS__)
#define glTexParameterfv(...) GLES2_DEFINE_OVERS_CONTEXT.glTexParameterfv(__VA_ARGS__)
#define glTexParameteri(...) GLES2_DEFINE_OVERS_CONTEXT.glTexParameteri(__VA_ARGS__)
#define glTexParameteriv(...) GLES2_DEFINE_OVERS_CONTEXT.glTexParameteriv(__VA_ARGS__)
#define glTexSubImage2D(...) GLES2_DEFINE_OVERS_CONTEXT.glTexSubImage2D(__VA_ARGS__)
#define glUniform1f(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform1f(__VA_ARGS__)
#define glUniform1fv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform1fv(__VA_ARGS__)
#define glUniform1i(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform1i(__VA_ARGS__)
#define glUniform1iv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform1iv(__VA_ARGS__)
#define glUniform2f(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform2f(__VA_ARGS__)
#define glUniform2fv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform2fv(__VA_ARGS__)
#define glUniform2i(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform2i(__VA_ARGS__)
#define glUniform2iv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform2iv(__VA_ARGS__)
#define glUniform3f(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform3f(__VA_ARGS__)
#define glUniform3fv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform3fv(__VA_ARGS__)
#define glUniform3i(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform3i(__VA_ARGS__)
#define glUniform3iv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform3iv(__VA_ARGS__)
#define glUniform4f(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform4f(__VA_ARGS__)
#define glUniform4fv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform4fv(__VA_ARGS__)
#define glUniform4i(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform4i(__VA_ARGS__)
#define glUniform4iv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniform4iv(__VA_ARGS__)
#define glUniformMatrix2fv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniformMatrix2fv(__VA_ARGS__)
#define glUniformMatrix3fv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniformMatrix3fv(__VA_ARGS__)
#define glUniformMatrix4fv(...) GLES2_DEFINE_OVERS_CONTEXT.glUniformMatrix4fv(__VA_ARGS__)
#define glUseProgram(...) GLES2_DEFINE_OVERS_CONTEXT.glUseProgram(__VA_ARGS__)
#define glValidateProgram(...) GLES2_DEFINE_OVERS_CONTEXT.glValidateProgram(__VA_ARGS__)
#define glVertexAttrib1f(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib1f(__VA_ARGS__)
#define glVertexAttrib1fv(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib1fv(__VA_ARGS__)
#define glVertexAttrib2f(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib2f(__VA_ARGS__)
#define glVertexAttrib2fv(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib2fv(__VA_ARGS__)
#define glVertexAttrib3f(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib3f(__VA_ARGS__)
#define glVertexAttrib3fv(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib3fv(__VA_ARGS__)
#define glVertexAttrib4f(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib4f(__VA_ARGS__)
#define glVertexAttrib4fv(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttrib4fv(__VA_ARGS__)
#define glVertexAttribPointer(...) GLES2_DEFINE_OVERS_CONTEXT.glVertexAttribPointer(__VA_ARGS__)
#define glViewport(...) GLES2_DEFINE_OVERS_CONTEXT.glViewport(__VA_ARGS__)
#define glBindVertexArrayOES(...) GLES2_DEFINE_OVERS_CONTEXT.glBindVertexArrayOES(__VA_ARGS__)
#define glDeleteVertexArraysOES(...) GLES2_DEFINE_OVERS_CONTEXT.glDeleteVertexArraysOES(__VA_ARGS__)
#define glGenVertexArraysOES(...) GLES2_DEFINE_OVERS_CONTEXT.glGenVertexArraysOES(__VA_ARGS__)
#define glIsVertexArrayOES(...) GLES2_DEFINE_OVERS_CONTEXT.glIsVertexArrayOES(__VA_ARGS__)


/* there is also a wrapper system for linking, but that is slower */
#endif // _H_GLES_DEFINE_OVERS

