/* generated with convert_gl2_h_into_gles2funcs_h.sno 
  Generator by Hibbard M. Engler

  */

SDL_PROC(void, glActiveTexture, (GLenum))
SDL_PROC(void, glAttachShader, (GLuint,GLuint))
SDL_PROC(void, glBindAttribLocation, (GLuint,GLuint,const GLchar *))
SDL_PROC(void, glBindBuffer, (GLenum,GLuint))
SDL_PROC(void, glBindFramebuffer, (GLenum,GLuint))
SDL_PROC(void, glBindRenderbuffer, (GLenum,GLuint))
SDL_PROC(void, glBindTexture, (GLenum,GLuint))
SDL_PROC(void, glBlendColor, (GLfloat,GLfloat,GLfloat,GLfloat))
SDL_PROC(void, glBlendEquation, (GLenum))
SDL_PROC(void, glBlendEquationSeparate, (GLenum,GLenum))
SDL_PROC(void, glBlendFunc, (GLenum,GLenum))
SDL_PROC(void, glBlendFuncSeparate, (GLenum,GLenum,GLenum,GLenum))
SDL_PROC(void, glBufferData, (GLenum,GLsizeiptr,const void *,GLenum))
SDL_PROC(void, glBufferSubData, (GLenum,GLintptr,GLsizeiptr,const void *))
SDL_PROC(GLenum, glCheckFramebufferStatus, (GLenum))
SDL_PROC(void, glClear, (GLbitfield))
SDL_PROC(void, glClearColor, (GLfloat,GLfloat,GLfloat,GLfloat))
SDL_PROC(void, glClearDepthf, (GLfloat))
SDL_PROC(void, glClearStencil, (GLint))
SDL_PROC(void, glColorMask, (GLboolean,GLboolean,GLboolean,GLboolean))
SDL_PROC(void, glCompileShader, (GLuint))
SDL_PROC(void, glCompressedTexImage2D, (GLenum,GLint,GLenum,GLsizei,GLsizei,GLint,GLsizei,const void *))
SDL_PROC(void, glCompressedTexSubImage2D, (GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLsizei,const void *))
SDL_PROC(void, glCopyTexImage2D, (GLenum,GLint,GLenum,GLint,GLint,GLsizei,GLsizei,GLint))
SDL_PROC(void, glCopyTexSubImage2D, (GLenum,GLint,GLint,GLint,GLint,GLint,GLsizei,GLsizei))
SDL_PROC(GLuint, glCreateProgram, (void))
SDL_PROC(GLuint, glCreateShader, (GLenum))
SDL_PROC(void, glCullFace, (GLenum))
SDL_PROC(void, glDeleteBuffers, (GLsizei,const GLuint *))
SDL_PROC(void, glDeleteFramebuffers, (GLsizei,const GLuint *))
SDL_PROC(void, glDeleteProgram, (GLuint))
SDL_PROC(void, glDeleteRenderbuffers, (GLsizei,const GLuint *))
SDL_PROC(void, glDeleteShader, (GLuint))
SDL_PROC(void, glDeleteTextures, (GLsizei,const GLuint *))
SDL_PROC(void, glDepthFunc, (GLenum))
SDL_PROC(void, glDepthMask, (GLboolean))
SDL_PROC(void, glDepthRangef, (GLfloat,GLfloat))
SDL_PROC(void, glDetachShader, (GLuint,GLuint))
SDL_PROC(void, glDisable, (GLenum))
SDL_PROC(void, glDisableVertexAttribArray, (GLuint))
SDL_PROC(void, glDrawArrays, (GLenum,GLint,GLsizei))
SDL_PROC(void, glDrawElements, (GLenum,GLsizei,GLenum,const void *))
SDL_PROC(void, glEnable, (GLenum))
SDL_PROC(void, glEnableVertexAttribArray, (GLuint))
SDL_PROC(void, glFinish, (void))
SDL_PROC(void, glFlush, (void))
SDL_PROC(void, glFramebufferRenderbuffer, (GLenum,GLenum,GLenum,GLuint))
SDL_PROC(void, glFramebufferTexture2D, (GLenum,GLenum,GLenum,GLuint,GLint))
SDL_PROC(void, glFrontFace, (GLenum))
SDL_PROC(void, glGenBuffers, (GLsizei,GLuint *))
SDL_PROC(void, glGenerateMipmap, (GLenum))
SDL_PROC(void, glGenFramebuffers, (GLsizei,GLuint *))
SDL_PROC(void, glGenRenderbuffers, (GLsizei,GLuint *))
SDL_PROC(void, glGenTextures, (GLsizei,GLuint *))
SDL_PROC(void, glGetActiveAttrib, (GLuint,GLuint,GLsizei,GLsizei *,GLint *,GLenum *,GLchar *))
SDL_PROC(void, glGetActiveUniform, (GLuint,GLuint,GLsizei,GLsizei *,GLint *,GLenum *,GLchar *))
SDL_PROC(void, glGetAttachedShaders, (GLuint,GLsizei,GLsizei *,GLuint *))
SDL_PROC(GLint, glGetAttribLocation, (GLuint,const GLchar *))
SDL_PROC(void, glGetBooleanv, (GLenum,GLboolean *))
SDL_PROC(void, glGetBufferParameteriv, (GLenum,GLenum,GLint *))
SDL_PROC(GLenum, glGetError, (void))
SDL_PROC(void, glGetFloatv, (GLenum,GLfloat *))
SDL_PROC(void, glGetFramebufferAttachmentParameteriv, (GLenum,GLenum,GLenum,GLint *))
SDL_PROC(void, glGetIntegerv, (GLenum,GLint *))
SDL_PROC(void, glGetProgramiv, (GLuint,GLenum,GLint *))
SDL_PROC(void, glGetProgramInfoLog, (GLuint,GLsizei,GLsizei *,GLchar *))
SDL_PROC(void, glGetRenderbufferParameteriv, (GLenum,GLenum,GLint *))
SDL_PROC(void, glGetShaderiv, (GLuint,GLenum,GLint *))
SDL_PROC(void, glGetShaderInfoLog, (GLuint,GLsizei,GLsizei *,GLchar *))
SDL_PROC(void, glGetShaderPrecisionFormat, (GLenum,GLenum,GLint *,GLint *))
SDL_PROC(void, glGetShaderSource, (GLuint,GLsizei,GLsizei *,GLchar *))
SDL_PROC(const GLubyte *, glGetString, (GLenum))
SDL_PROC(void, glGetTexParameterfv, (GLenum,GLenum,GLfloat *))
SDL_PROC(void, glGetTexParameteriv, (GLenum,GLenum,GLint *))
SDL_PROC(void, glGetUniformfv, (GLuint,GLint,GLfloat *))
SDL_PROC(void, glGetUniformiv, (GLuint,GLint,GLint *))
SDL_PROC(GLint, glGetUniformLocation, (GLuint,const GLchar *))
SDL_PROC(void, glGetVertexAttribfv, (GLuint,GLenum,GLfloat *))
SDL_PROC(void, glGetVertexAttribiv, (GLuint,GLenum,GLint *))
SDL_PROC(void, glGetVertexAttribPointerv, (GLuint,GLenum,void **))
SDL_PROC(void, glHint, (GLenum,GLenum))
SDL_PROC(GLboolean, glIsBuffer, (GLuint))
SDL_PROC(GLboolean, glIsEnabled, (GLenum))
SDL_PROC(GLboolean, glIsFramebuffer, (GLuint))
SDL_PROC(GLboolean, glIsProgram, (GLuint))
SDL_PROC(GLboolean, glIsRenderbuffer, (GLuint))
SDL_PROC(GLboolean, glIsShader, (GLuint))
SDL_PROC(GLboolean, glIsTexture, (GLuint))
SDL_PROC(void, glLineWidth, (GLfloat))
SDL_PROC(void, glLinkProgram, (GLuint))
SDL_PROC(void, glPixelStorei, (GLenum,GLint))
SDL_PROC(void, glPolygonOffset, (GLfloat,GLfloat))
SDL_PROC(void, glReadPixels, (GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,void *))
SDL_PROC(void, glReleaseShaderCompiler, (void))
SDL_PROC(void, glRenderbufferStorage, (GLenum,GLenum,GLsizei,GLsizei))
SDL_PROC(void, glSampleCoverage, (GLfloat,GLboolean))
SDL_PROC(void, glScissor, (GLint,GLint,GLsizei,GLsizei))
SDL_PROC(void, glShaderBinary, (GLsizei,const GLuint *,GLenum,const void *,GLsizei))
SDL_PROC(void, glShaderSource, (GLuint,GLsizei,const GLchar *const*,const GLint *))
SDL_PROC(void, glStencilFunc, (GLenum,GLint,GLuint))
SDL_PROC(void, glStencilFuncSeparate, (GLenum,GLenum,GLint,GLuint))
SDL_PROC(void, glStencilMask, (GLuint))
SDL_PROC(void, glStencilMaskSeparate, (GLenum,GLuint))
SDL_PROC(void, glStencilOp, (GLenum,GLenum,GLenum))
SDL_PROC(void, glStencilOpSeparate, (GLenum,GLenum,GLenum,GLenum))
SDL_PROC(void, glTexImage2D, (GLenum,GLint,GLint,GLsizei,GLsizei,GLint,GLenum,GLenum,const void *))
SDL_PROC(void, glTexParameterf, (GLenum,GLenum,GLfloat))
SDL_PROC(void, glTexParameterfv, (GLenum,GLenum,const GLfloat *))
SDL_PROC(void, glTexParameteri, (GLenum,GLenum,GLint))
SDL_PROC(void, glTexParameteriv, (GLenum,GLenum,const GLint *))
SDL_PROC(void, glTexSubImage2D, (GLenum,GLint,GLint,GLint,GLsizei,GLsizei,GLenum,GLenum,const void *))
SDL_PROC(void, glUniform1f, (GLint,GLfloat))
SDL_PROC(void, glUniform1fv, (GLint,GLsizei,const GLfloat *))
SDL_PROC(void, glUniform1i, (GLint,GLint))
SDL_PROC(void, glUniform1iv, (GLint,GLsizei,const GLint *))
SDL_PROC(void, glUniform2f, (GLint,GLfloat,GLfloat))
SDL_PROC(void, glUniform2fv, (GLint,GLsizei,const GLfloat *))
SDL_PROC(void, glUniform2i, (GLint,GLint,GLint))
SDL_PROC(void, glUniform2iv, (GLint,GLsizei,const GLint *))
SDL_PROC(void, glUniform3f, (GLint,GLfloat,GLfloat,GLfloat))
SDL_PROC(void, glUniform3fv, (GLint,GLsizei,const GLfloat *))
SDL_PROC(void, glUniform3i, (GLint,GLint,GLint,GLint))
SDL_PROC(void, glUniform3iv, (GLint,GLsizei,const GLint *))
SDL_PROC(void, glUniform4f, (GLint,GLfloat,GLfloat,GLfloat,GLfloat))
SDL_PROC(void, glUniform4fv, (GLint,GLsizei,const GLfloat *))
SDL_PROC(void, glUniform4i, (GLint,GLint,GLint,GLint,GLint))
SDL_PROC(void, glUniform4iv, (GLint,GLsizei,const GLint *))
SDL_PROC(void, glUniformMatrix2fv, (GLint,GLsizei,GLboolean,const GLfloat *))
SDL_PROC(void, glUniformMatrix3fv, (GLint,GLsizei,GLboolean,const GLfloat *))
SDL_PROC(void, glUniformMatrix4fv, (GLint,GLsizei,GLboolean,const GLfloat *))
SDL_PROC(void, glUseProgram, (GLuint))
SDL_PROC(void, glValidateProgram, (GLuint))
SDL_PROC(void, glVertexAttrib1f, (GLuint,GLfloat))
SDL_PROC(void, glVertexAttrib1fv, (GLuint,const GLfloat *))
SDL_PROC(void, glVertexAttrib2f, (GLuint,GLfloat,GLfloat))
SDL_PROC(void, glVertexAttrib2fv, (GLuint,const GLfloat *))
SDL_PROC(void, glVertexAttrib3f, (GLuint,GLfloat,GLfloat,GLfloat))
SDL_PROC(void, glVertexAttrib3fv, (GLuint,const GLfloat *))
SDL_PROC(void, glVertexAttrib4f, (GLuint,GLfloat,GLfloat,GLfloat,GLfloat))
SDL_PROC(void, glVertexAttrib4fv, (GLuint,const GLfloat *))
SDL_PROC(void, glVertexAttribPointer, (GLuint,GLint,GLenum,GLboolean,GLsizei,const void *))
SDL_PROC(void, glViewport, (GLint,GLint,GLsizei,GLsizei))
SDL_PROC(void, glBindVertexArrayOES, (GLuint))
SDL_PROC(void, glDeleteVertexArraysOES, (GLsizei,const GLuint *))
SDL_PROC(void, glGenVertexArraysOES, (GLsizei,GLuint *))
SDL_PROC(GLboolean, glIsVertexArrayOES, (GLuint))


