/* Autogenerated by hxtools bin2c */
#ifndef ZCOOL_XIAOWEI_H
#define ZCOOL_XIAOWEI_H 1

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char bin2c_ZCOOLXiaoWei_Regular_ttf[6313808];

#ifdef __cplusplus
} /* extern "C" */
#endif


#endif /* ZCOOL_XIAOWEI_H */
