#!/bin/bash
export SR_BIN="${SR_BIN:-/usr/local/bin}"
#export APACHE_LOG_DIR="${APACHE_LOG_DIR:-/var/log/apache2}"
#export SR_LOG_DIR="${SR_LOG_DIR:-/var/log/sr}"
#cd $APACHE_LOG_DIR


if [ $# -ne 1 ]; then
  echo 2>&1 "Usage: $0 <station_name> where <station_name> is something like ds.silentradiance.com"
  exit 2
fi

#export MIDFILE=$SR_LOG_DIR/all_`date +%y%m%d`.gz


#get_all_sr_error_log | gzip >$MIDFILE

sbl <songs.dat -i2048k -s4M -m1M  -u $1 $SR_BIN/convert_songs_dat_to_sql.sbl  | tee a | \
 mysql  -s -h dtb.silentradiance.com -u station_recorder sr
#snobol4 <songs.dat  -u $1 $SR_BIN/convert_songs_dat_to_sql.sbl  | tee a |mysql -s -h dtb.silentradiance.com -u station_recorder sr

#grant select,insert on sr.sr_stations to 'station_recorder'@'64.13.145.233 identified by 
#grant select,insert on sr.sr_hash_codes to 'station_recorder'@'64.13.145.233 identified by 
#grant select,insert on sr.sr_hash_code_links to 'station_recorder'@'64.13.145.233 identified by 
#grant select,insert on sr.sr_radio_plays to 'station_recorder'@'64.13.145.233 identified by 

#grant select,insert on sr.sr_station_web_programs to 'station_recorder'@'64.13.145.233 identified by 
#grant select,insert on sr.sr_song_info to 'station_recorder'@'64.13.145.233 identified by 
#grant select,insert on sr.sr_picture_info to 'station_recorder'@'64.13.145.233 identified by 

#convert_songs_dat_to_sql.sbl




#redo_all_sr_error_log
